spring.application.name=ms-mascotas

spring.datasource.url=jdbc:postgresql://localhost:5432/ms_mascotas
spring.datasource.username=postgres
spring.datasource.password=tu_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect